# Generated by Django 3.0.8 on 2020-07-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faculty_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_exam', models.DateField(blank=True, default=None)),
                ('no_of_blocks', models.SmallIntegerField(blank=True, default=None)),
                ('session', models.CharField(choices=[('MORNING', 'MORNING'), ('EVENING', 'EVENING')], default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answer_sheets', models.SmallIntegerField(default=None)),
                ('first_ans_sheet', models.SmallIntegerField(default=None)),
                ('last_ans_sheet', models.SmallIntegerField(default=None)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subject')),
            ],
        ),
    ]
