# Generated by Django 3.0.8 on 2020-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_assessmentdetail_examblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdetail',
            name='first_ans_sheet',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='last_ans_sheet',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
