# Generated by Django 3.0.8 on 2020-07-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200717_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answer_sheets', models.SmallIntegerField(default=None)),
                ('first_ans_sheet', models.CharField(default=None, max_length=10)),
                ('last_ans_sheet', models.CharField(default=None, max_length=10)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='assessment',
            field=models.ManyToManyField(to='home.Assessment'),
        ),
    ]
