# Generated by Django 3.0.8 on 2020-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200717_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperChecked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_sheet_no', models.CharField(max_length=10)),
                ('checked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='checked',
            field=models.ManyToManyField(to='home.PaperChecked'),
        ),
    ]
