# Generated by Django 3.0.8 on 2020-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200717_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperchecked',
            name='marks',
            field=models.SmallIntegerField(default=None),
        ),
    ]
